# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'CPhotoFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CPhotoFeed
  
  pod 'Pastel'
  pod 'Alamofire'
  pod 'Anchors', :git => 'https://github.com/onmyway133/Anchors'
  pod 'Kingfisher'
  pod 'Compass'

  target 'CPhotoFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CPhotoFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
